name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push nikto image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: securecodebox/nikto/nikto
          tag_with_ref: true
          tag_with_sha: true
